---
name: release binary

on:
  release:
    types: [created]

jobs:
  release-alpine-static:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Docker compose
        run: STAKE_TOKEN="tubaobab" TIMEOUT_COMMIT=500ms docker-compose up -d

      - name: Copy binary
        run: docker cp juno_node_1:/usr/bin/baobabd ./baobabd

      - name: Save sha256 sum
        run: sha256sum ./baobabd > ./baobabd_sha256.txt

      - name: Release
        uses: softprops/action-gh-release@v1        
        with:
          token: ${{ github.token }}
          files: |
            baobabd
            baobabd_sha256.txt

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
